apiVersion: v1
kind: Service
metadata:
  name: backend-service # TODO: Specify a unique service name if deploying multiple services
spec:
  type: ClusterIP
  selector:
    app: flask-backend
  ports:
    - port: 5001
      targetPort: 5001